==11359== Memcheck, a memory error detector
==11359== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==11359== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==11359== Command: /home/wasmer/repositories/wasmer/wasmer/target/debug/examples/early-exit
==11359== 
==11359== 
==11359== HEAP SUMMARY:
==11359==     in use at exit: 26,760 bytes in 87 blocks
==11359==   total heap usage: 759 allocs, 672 frees, 143,505 bytes allocated
==11359== 
==11359== 16 bytes in 1 blocks are still reachable in loss record 1 of 31
==11359==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11359==    by 0x1A54D5B: alloc::alloc::alloc (alloc.rs:80)
==11359==    by 0x1A56133: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11359==    by 0x1A54CBC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11359==    by 0x1AAC7FD: new<std::sync::mutex::Mutex<()>> (boxed.rs:177)
==11359==    by 0x1AAC7FD: backtrace::lock::lock::{{closure}} (lib.rs:134)
==11359==    by 0x1AA6D5F: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11359==    by 0x1C326D9: std::sync::once::Once::call_inner (once.rs:416)
==11359==    by 0x1AA6CD8: std::sync::once::Once::call_once (once.rs:264)
==11359==    by 0x1AAC732: backtrace::lock::lock (lib.rs:133)
==11359==    by 0x1A47FEB: backtrace::backtrace::trace (mod.rs:52)
==11359==    by 0x1A8416C: backtrace::capture::Backtrace::create (capture.rs:176)
==11359==    by 0x1A840E3: backtrace::capture::Backtrace::new_unresolved (capture.rs:170)
==11359== 
==11359== 32 bytes in 1 blocks are still reachable in loss record 2 of 31
==11359==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11359==    by 0x4E3F7F4: _dlerror_run (dlerror.c:140)
==11359==    by 0x4E3F165: dlsym (dlsym.c:70)
==11359==    by 0x1C47603: fetch (weak.rs:61)
==11359==    by 0x1C47603: get<unsafe extern "C" fn(*const libc::unix::linux_like::linux::gnu::b64::x86_64::pthread_attr_t) -> usize> (weak.rs:46)
==11359==    by 0x1C47603: min_stack_size (thread.rs:449)
==11359==    by 0x1C47603: std::sys::unix::thread::Thread::new (thread.rs:49)
==11359==    by 0xD7777B: std::thread::Builder::spawn_unchecked (mod.rs:492)
==11359==    by 0xD799FB: std::thread::Builder::spawn (mod.rs:386)
==11359==    by 0xD484E8: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11359==    by 0xD4962F: rayon_core::registry::Registry::new (registry.rs:256)
==11359==    by 0xD4875D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11359==    by 0xD48C19: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11359==    by 0xD6C2E3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11359==    by 0x1C326D9: std::sync::once::Once::call_inner (once.rs:416)
==11359== 
==11359== 40 bytes in 1 blocks are still reachable in loss record 3 of 31
==11359==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11359==    by 0x1A54D5B: alloc::alloc::alloc (alloc.rs:80)
==11359==    by 0x1A56133: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11359==    by 0x1A54CBC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11359==    by 0x1A861AC: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==11359==    by 0x1AAC7EE: backtrace::lock::lock::{{closure}} (lib.rs:134)
==11359==    by 0x1AA6D5F: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11359==    by 0x1C326D9: std::sync::once::Once::call_inner (once.rs:416)
==11359==    by 0x1AA6CD8: std::sync::once::Once::call_once (once.rs:264)
==11359==    by 0x1AAC732: backtrace::lock::lock (lib.rs:133)
==11359==    by 0x1A47FEB: backtrace::backtrace::trace (mod.rs:52)
==11359==    by 0x1A8416C: backtrace::capture::Backtrace::create (capture.rs:176)
==11359== 
==11359== 64 bytes in 4 blocks are still reachable in loss record 4 of 31
==11359==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11359==    by 0xD7223B: alloc::alloc::alloc (alloc.rs:80)
==11359==    by 0xD73063: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11359==    by 0xD7219C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11359==    by 0xD586E6: new<crossbeam_deque::deque::Buffer<rayon_core::job::JobRef>> (boxed.rs:177)
==11359==    by 0xD586E6: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==11359==    by 0xD73F03: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==11359==    by 0xD74053: crossbeam_epoch::atomic::Atomic<T>::init (atomic.rs:309)
==11359==    by 0xD74023: crossbeam_epoch::atomic::Atomic<T>::new (atomic.rs:294)
==11359==    by 0xD56DE6: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:253)
==11359==    by 0xD49AAE: rayon_core::registry::Registry::new::{{closure}} (registry.rs:225)
==11359==    by 0xD827FC: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11359==    by 0xD51B7D: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11359== 
==11359== 64 bytes in 4 blocks are still reachable in loss record 5 of 31
==11359==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11359==    by 0x1C4755C: alloc (alloc.rs:80)
==11359==    by 0x1C4755C: alloc (alloc.rs:174)
==11359==    by 0x1C4755C: exchange_malloc (alloc.rs:277)
==11359==    by 0x1C4755C: std::sys::unix::thread::Thread::new (thread.rs:44)
==11359==    by 0xD7777B: std::thread::Builder::spawn_unchecked (mod.rs:492)
==11359==    by 0xD799FB: std::thread::Builder::spawn (mod.rs:386)
==11359==    by 0xD484E8: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11359==    by 0xD4962F: rayon_core::registry::Registry::new (registry.rs:256)
==11359==    by 0xD4875D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11359==    by 0xD48C19: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11359==    by 0xD6C2E3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11359==    by 0x1C326D9: std::sync::once::Once::call_inner (once.rs:416)
==11359==    by 0xD6C080: std::sync::once::Once::call_once (once.rs:264)
==11359==    by 0xD48A66: rayon_core::registry::set_global_registry (registry.rs:194)
==11359== 
==11359== 72 bytes in 1 blocks are still reachable in loss record 6 of 31
==11359==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11359==    by 0x1830F0B: alloc::alloc::alloc (alloc.rs:80)
==11359==    by 0x1831033: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11359==    by 0x1830E6C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11359==    by 0x1833D27: std::sync::rwlock::RwLock<T>::new (rwlock.rs:134)
==11359==    by 0x183405C: <std::sync::rwlock::RwLock<T> as core::default::Default>::default (rwlock.rs:451)
==11359==    by 0x18259D0: __static_ref_initialize (frame_info.rs:28)
==11359==    by 0x18259D0: core::ops::function::FnOnce::call_once (function.rs:233)
==11359==    by 0x185D6EB: lazy_static::lazy::Lazy<T>::get::{{closure}} (inline_lazy.rs:31)
==11359==    by 0x185C064: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11359==    by 0x1C326D9: std::sync::once::Once::call_inner (once.rs:416)
==11359==    by 0x185BFE0: std::sync::once::Once::call_once (once.rs:264)
==11359==    by 0x1820DF8: get<std::sync::rwlock::RwLock<wasmer_engine::trap::frame_info::GlobalFrameInfo>,fn() -> std::sync::rwlock::RwLock<wasmer_engine::trap::frame_info::GlobalFrameInfo>> (inline_lazy.rs:30)
==11359==    by 0x1820DF8: __stability (lib.rs:142)
==11359==    by 0x1820DF8: <wasmer_engine::trap::frame_info::FRAME_INFO as core::ops::deref::Deref>::deref (lib.rs:144)
==11359== 
==11359== 96 bytes in 3 blocks are still reachable in loss record 7 of 31
==11359==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11359==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==11359==    by 0x1C13B8E: register_dtor (fast_thread_local.rs:33)
==11359==    by 0x1C13B8E: try_register_dtor<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:438)
==11359==    by 0x1C13B8E: std::thread::local::fast::Key<T>::try_initialize (local.rs:424)
==11359==    by 0x1C36389: get<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,fn() -> core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:410)
==11359==    by 0x1C36389: __getit (local.rs:175)
==11359==    by 0x1C36389: try_with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:262)
==11359==    by 0x1C36389: with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:239)
==11359==    by 0x1C36389: std::sys_common::thread_info::set (thread_info.rs:40)
==11359==    by 0xD78C11: std::thread::Builder::spawn_unchecked::{{closure}} (mod.rs:473)
==11359==    by 0xD6D22E: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==11359==    by 0x1C47979: call_once<(),FnOnce<()>> (boxed.rs:1081)
==11359==    by 0x1C47979: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==11359==    by 0x1C47979: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==11359==    by 0x52516DA: start_thread (pthread_create.c:463)
==11359==    by 0x57A271E: clone (clone.S:95)
==11359== 
==11359== 96 bytes in 3 blocks are still reachable in loss record 8 of 31
==11359==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11359==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==11359==    by 0xDB0A81: std::thread::local::fast::Key<T>::try_register_dtor (local.rs:438)
==11359==    by 0xDB0982: std::thread::local::fast::Key<T>::try_initialize (local.rs:424)
==11359==    by 0xDB0B26: std::thread::local::fast::Key<T>::get (local.rs:410)
==11359==    by 0xDB087C: crossbeam_epoch::default::HANDLE::__getit (local.rs:175)
==11359==    by 0xD5BAF4: std::thread::local::LocalKey<T>::try_with (local.rs:262)
==11359==    by 0xD5FF82: crossbeam_epoch::default::with_handle (default.rs:43)
==11359==    by 0xD601E6: crossbeam_epoch::default::is_pinned (default.rs:30)
==11359==    by 0xD56FAC: crossbeam_deque::deque::Stealer<T>::steal (deque.rs:619)
==11359==    by 0xD4B912: rayon_core::registry::WorkerThread::steal::{{closure}} (registry.rs:775)
==11359==    by 0xD46DAC: core::iter::traits::iterator::Iterator::find_map::check::{{closure}} (iterator.rs:2258)
==11359== 
==11359== 160 bytes in 4 blocks are still reachable in loss record 9 of 31
==11359==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11359==    by 0xD7223B: alloc::alloc::alloc (alloc.rs:80)
==11359==    by 0xD73063: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11359==    by 0xD7219C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11359==    by 0xD76F5F: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==11359==    by 0xD8A670: rayon_core::latch::LockLatch::new (latch.rs:230)
==11359==    by 0xD4A85C: rayon_core::registry::ThreadInfo::new (registry.rs:579)
==11359==    by 0xD6D021: core::ops::function::FnMut::call_mut (function.rs:154)
==11359==    by 0xD82FE3: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11359==    by 0xD66003: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11359==    by 0xD83CC8: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11359==    by 0xD81E89: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11359== 
==11359== 160 bytes in 4 blocks are still reachable in loss record 10 of 31
==11359==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11359==    by 0xD7223B: alloc::alloc::alloc (alloc.rs:80)
==11359==    by 0xD73063: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11359==    by 0xD7219C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11359==    by 0xD76F5F: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==11359==    by 0xD8A670: rayon_core::latch::LockLatch::new (latch.rs:230)
==11359==    by 0xD4A874: rayon_core::registry::ThreadInfo::new (registry.rs:580)
==11359==    by 0xD6D021: core::ops::function::FnMut::call_mut (function.rs:154)
==11359==    by 0xD82FE3: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11359==    by 0xD66003: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11359==    by 0xD83CC8: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11359==    by 0xD81E89: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11359== 
==11359== 160 bytes in 4 blocks are still reachable in loss record 11 of 31
==11359==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11359==    by 0xD7223B: alloc::alloc::alloc (alloc.rs:80)
==11359==    by 0xD73063: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11359==    by 0xD7219C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11359==    by 0xD76F5F: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==11359==    by 0xD7A823: <std::sync::mutex::Mutex<T> as core::default::Default>::default (mutex.rs:446)
==11359==    by 0xD654CE: <rayon_core::sleep::WorkerSleepState as core::default::Default>::default (mod.rs:55)
==11359==    by 0xD6297D: <crossbeam_utils::cache_padded::CachePadded<T> as core::default::Default>::default (cache_padded.rs:77)
==11359==    by 0xD63D6A: rayon_core::sleep::Sleep::new::{{closure}} (mod.rs:67)
==11359==    by 0xD82CB0: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11359==    by 0xD51E58: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11359==    by 0xD83C09: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11359== 
==11359== 160 bytes in 4 blocks are still reachable in loss record 12 of 31
==11359==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11359==    by 0x1C14F2E: alloc (alloc.rs:80)
==11359==    by 0x1C14F2E: alloc (alloc.rs:174)
==11359==    by 0x1C14F2E: exchange_malloc (alloc.rs:277)
==11359==    by 0x1C14F2E: new<()> (mutex.rs:223)
==11359==    by 0x1C14F2E: std::thread::Thread::new (mod.rs:1149)
==11359==    by 0xD7751D: std::thread::Builder::spawn_unchecked (mod.rs:462)
==11359==    by 0xD799FB: std::thread::Builder::spawn (mod.rs:386)
==11359==    by 0xD484E8: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11359==    by 0xD4962F: rayon_core::registry::Registry::new (registry.rs:256)
==11359==    by 0xD4875D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11359==    by 0xD48C19: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11359==    by 0xD6C2E3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11359==    by 0x1C326D9: std::sync::once::Once::call_inner (once.rs:416)
==11359==    by 0xD6C080: std::sync::once::Once::call_once (once.rs:264)
==11359==    by 0xD48A66: rayon_core::registry::set_global_registry (registry.rs:194)
==11359== 
==11359== 160 bytes in 4 blocks are still reachable in loss record 13 of 31
==11359==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11359==    by 0xD7223B: alloc::alloc::alloc (alloc.rs:80)
==11359==    by 0xD73063: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11359==    by 0xD7219C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11359==    by 0xD41B67: alloc::sync::Arc<T>::new (sync.rs:324)
==11359==    by 0xD775BB: std::thread::Builder::spawn_unchecked (mod.rs:465)
==11359==    by 0xD799FB: std::thread::Builder::spawn (mod.rs:386)
==11359==    by 0xD484E8: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11359==    by 0xD4962F: rayon_core::registry::Registry::new (registry.rs:256)
==11359==    by 0xD4875D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11359==    by 0xD48C19: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11359==    by 0xD6C2E3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11359== 
==11359== 192 bytes in 4 blocks are still reachable in loss record 14 of 31
==11359==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11359==    by 0x1C32026: alloc (alloc.rs:80)
==11359==    by 0x1C32026: alloc (alloc.rs:174)
==11359==    by 0x1C32026: exchange_malloc (alloc.rs:277)
==11359==    by 0x1C32026: std::sync::condvar::Condvar::new (condvar.rs:130)
==11359==    by 0xD8A68C: rayon_core::latch::LockLatch::new (latch.rs:231)
==11359==    by 0xD4A85C: rayon_core::registry::ThreadInfo::new (registry.rs:579)
==11359==    by 0xD6D021: core::ops::function::FnMut::call_mut (function.rs:154)
==11359==    by 0xD82FE3: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11359==    by 0xD66003: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11359==    by 0xD83CC8: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11359==    by 0xD81E89: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11359==    by 0xD69E81: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==11359==    by 0xD6A564: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11359==    by 0xD6B696: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==11359== 
==11359== 192 bytes in 4 blocks are still reachable in loss record 15 of 31
==11359==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11359==    by 0x1C32026: alloc (alloc.rs:80)
==11359==    by 0x1C32026: alloc (alloc.rs:174)
==11359==    by 0x1C32026: exchange_malloc (alloc.rs:277)
==11359==    by 0x1C32026: std::sync::condvar::Condvar::new (condvar.rs:130)
==11359==    by 0xD8A68C: rayon_core::latch::LockLatch::new (latch.rs:231)
==11359==    by 0xD4A874: rayon_core::registry::ThreadInfo::new (registry.rs:580)
==11359==    by 0xD6D021: core::ops::function::FnMut::call_mut (function.rs:154)
==11359==    by 0xD82FE3: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11359==    by 0xD66003: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11359==    by 0xD83CC8: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11359==    by 0xD81E89: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11359==    by 0xD69E81: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==11359==    by 0xD6A564: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11359==    by 0xD6B696: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==11359== 
==11359== 192 bytes in 4 blocks are still reachable in loss record 16 of 31
==11359==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11359==    by 0x1C32026: alloc (alloc.rs:80)
==11359==    by 0x1C32026: alloc (alloc.rs:174)
==11359==    by 0x1C32026: exchange_malloc (alloc.rs:277)
==11359==    by 0x1C32026: std::sync::condvar::Condvar::new (condvar.rs:130)
==11359==    by 0xD654EA: <rayon_core::sleep::WorkerSleepState as core::default::Default>::default (mod.rs:57)
==11359==    by 0xD6297D: <crossbeam_utils::cache_padded::CachePadded<T> as core::default::Default>::default (cache_padded.rs:77)
==11359==    by 0xD63D6A: rayon_core::sleep::Sleep::new::{{closure}} (mod.rs:67)
==11359==    by 0xD82CB0: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11359==    by 0xD51E58: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11359==    by 0xD83C09: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11359==    by 0xD81D5A: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11359==    by 0xD69A87: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==11359==    by 0xD6A6B1: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11359==    by 0xD6B6F5: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==11359== 
==11359== 192 bytes in 4 blocks are still reachable in loss record 17 of 31
==11359==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11359==    by 0x1C14F92: alloc (alloc.rs:80)
==11359==    by 0x1C14F92: alloc (alloc.rs:174)
==11359==    by 0x1C14F92: exchange_malloc (alloc.rs:277)
==11359==    by 0x1C14F92: new (condvar.rs:130)
==11359==    by 0x1C14F92: std::thread::Thread::new (mod.rs:1150)
==11359==    by 0xD7751D: std::thread::Builder::spawn_unchecked (mod.rs:462)
==11359==    by 0xD799FB: std::thread::Builder::spawn (mod.rs:386)
==11359==    by 0xD484E8: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11359==    by 0xD4962F: rayon_core::registry::Registry::new (registry.rs:256)
==11359==    by 0xD4875D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11359==    by 0xD48C19: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11359==    by 0xD6C2E3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11359==    by 0x1C326D9: std::sync::once::Once::call_inner (once.rs:416)
==11359==    by 0xD6C080: std::sync::once::Once::call_once (once.rs:264)
==11359==    by 0xD48A66: rayon_core::registry::set_global_registry (registry.rs:194)
==11359== 
==11359== 320 bytes in 4 blocks are still reachable in loss record 18 of 31
==11359==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11359==    by 0x1C14FE1: alloc (alloc.rs:80)
==11359==    by 0x1C14FE1: alloc (alloc.rs:174)
==11359==    by 0x1C14FE1: exchange_malloc (alloc.rs:277)
==11359==    by 0x1C14FE1: new<std::thread::Inner> (sync.rs:324)
==11359==    by 0x1C14FE1: std::thread::Thread::new (mod.rs:1145)
==11359==    by 0xD7751D: std::thread::Builder::spawn_unchecked (mod.rs:462)
==11359==    by 0xD799FB: std::thread::Builder::spawn (mod.rs:386)
==11359==    by 0xD484E8: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11359==    by 0xD4962F: rayon_core::registry::Registry::new (registry.rs:256)
==11359==    by 0xD4875D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11359==    by 0xD48C19: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11359==    by 0xD6C2E3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11359==    by 0x1C326D9: std::sync::once::Once::call_inner (once.rs:416)
==11359==    by 0xD6C080: std::sync::once::Once::call_once (once.rs:264)
==11359==    by 0xD48A66: rayon_core::registry::set_global_registry (registry.rs:194)
==11359== 
==11359== 384 bytes in 1 blocks are still reachable in loss record 19 of 31
==11359==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11359==    by 0xDD93EB: alloc::alloc::alloc (alloc.rs:80)
==11359==    by 0xDD9C93: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11359==    by 0xDD07AA: alloc::raw_vec::finish_grow (raw_vec.rs:497)
==11359==    by 0xD8DAF0: alloc::raw_vec::RawVec<T,A>::grow_amortized (raw_vec.rs:429)
==11359==    by 0xD8BD03: alloc::raw_vec::RawVec<T,A>::try_reserve (raw_vec.rs:310)
==11359==    by 0xD8F5C2: alloc::raw_vec::RawVec<T,A>::reserve (raw_vec.rs:300)
==11359==    by 0xD688A8: alloc::vec::Vec<T>::reserve (vec.rs:505)
==11359==    by 0xD69D97: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2136)
==11359==    by 0xD6A564: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11359==    by 0xD6B696: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==11359==    by 0xD81B18: core::iter::traits::iterator::Iterator::collect (iterator.rs:1671)
==11359== 
==11359== 416 bytes in 4 blocks are still reachable in loss record 20 of 31
==11359==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11359==    by 0xD7223B: alloc::alloc::alloc (alloc.rs:80)
==11359==    by 0xD73063: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11359==    by 0xD7219C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11359==    by 0xD776E7: new<closure-0> (boxed.rs:177)
==11359==    by 0xD776E7: std::thread::Builder::spawn_unchecked (mod.rs:494)
==11359==    by 0xD799FB: std::thread::Builder::spawn (mod.rs:386)
==11359==    by 0xD484E8: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11359==    by 0xD4962F: rayon_core::registry::Registry::new (registry.rs:256)
==11359==    by 0xD4875D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11359==    by 0xD48C19: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11359==    by 0xD6C2E3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11359==    by 0x1C326D9: std::sync::once::Once::call_inner (once.rs:416)
==11359== 
==11359== 512 bytes in 1 blocks are still reachable in loss record 21 of 31
==11359==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11359==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11359==    by 0x1C37A99: aligned_malloc (alloc.rs:95)
==11359==    by 0x1C37A99: alloc (alloc.rs:22)
==11359==    by 0x1C37A99: __rdl_alloc (alloc.rs:304)
==11359==    by 0xDD93EB: alloc::alloc::alloc (alloc.rs:80)
==11359==    by 0xDD9C93: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11359==    by 0xDD07AA: alloc::raw_vec::finish_grow (raw_vec.rs:497)
==11359==    by 0xD8D790: alloc::raw_vec::RawVec<T,A>::grow_amortized (raw_vec.rs:429)
==11359==    by 0xD8BC03: alloc::raw_vec::RawVec<T,A>::try_reserve (raw_vec.rs:310)
==11359==    by 0xD8F702: alloc::raw_vec::RawVec<T,A>::reserve (raw_vec.rs:300)
==11359==    by 0xD68878: alloc::vec::Vec<T>::reserve (vec.rs:505)
==11359==    by 0xD699C7: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2136)
==11359==    by 0xD6A6B1: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11359== 
==11359== 640 bytes in 1 blocks are still reachable in loss record 22 of 31
==11359==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11359==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11359==    by 0x1C37A99: aligned_malloc (alloc.rs:95)
==11359==    by 0x1C37A99: alloc (alloc.rs:22)
==11359==    by 0x1C37A99: __rdl_alloc (alloc.rs:304)
==11359==    by 0xD7223B: alloc::alloc::alloc (alloc.rs:80)
==11359==    by 0xD73063: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11359==    by 0xD7219C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11359==    by 0xD41995: alloc::sync::Arc<T>::new (sync.rs:324)
==11359==    by 0xD49227: rayon_core::registry::Registry::new (registry.rs:234)
==11359==    by 0xD4875D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11359==    by 0xD48C19: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11359==    by 0xD6C2E3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11359==    by 0x1C326D9: std::sync::once::Once::call_inner (once.rs:416)
==11359== 
==11359== 640 bytes in 1 blocks are still reachable in loss record 23 of 31
==11359==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11359==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11359==    by 0x1C37A99: aligned_malloc (alloc.rs:95)
==11359==    by 0x1C37A99: alloc (alloc.rs:22)
==11359==    by 0x1C37A99: __rdl_alloc (alloc.rs:304)
==11359==    by 0xDB52EB: alloc::alloc::alloc (alloc.rs:80)
==11359==    by 0xDB5833: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11359==    by 0xDB524C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11359==    by 0xDB14C5: alloc::sync::Arc<T>::new (sync.rs:324)
==11359==    by 0xDB1A09: <crossbeam_epoch::collector::Collector as core::default::Default>::default (collector.rs:32)
==11359==    by 0xDB1A36: crossbeam_epoch::collector::Collector::new (collector.rs:40)
==11359==    by 0xDAFF29: __static_ref_initialize (default.rs:13)
==11359==    by 0xDAFF29: core::ops::function::FnOnce::call_once (function.rs:233)
==11359==    by 0xDAFD95: lazy_static::lazy::Lazy<T>::get::{{closure}} (inline_lazy.rs:31)
==11359==    by 0xDB1054: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11359== 
==11359== 808 bytes in 1 blocks are still reachable in loss record 24 of 31
==11359==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11359==    by 0x1830F0B: alloc::alloc::alloc (alloc.rs:80)
==11359==    by 0x1831033: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11359==    by 0x1830E6C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11359==    by 0x183F0E0: new<alloc::collections::btree::node::LeafNode<usize, wasmer_engine::trap::frame_info::ModuleInfoFrameInfo>> (boxed.rs:177)
==11359==    by 0x183F0E0: alloc::collections::btree::node::Root<K,V>::new_leaf (node.rs:157)
==11359==    by 0x18259E9: core::ops::function::FnOnce::call_once (function.rs:233)
==11359==    by 0x183212C: core::option::Option<T>::get_or_insert_with (option.rs:853)
==11359==    by 0x18579EE: alloc::collections::btree::map::BTreeMap<K,V>::ensure_root_is_owned (map.rs:2324)
==11359==    by 0x1857DC1: alloc::collections::btree::map::BTreeMap<K,V>::entry (map.rs:1061)
==11359==    by 0x1858C39: alloc::collections::btree::map::BTreeMap<K,V>::insert (map.rs:829)
==11359==    by 0x1820B0F: wasmer_engine::trap::frame_info::register (frame_info.rs:281)
==11359==    by 0xBE9BD4: <wasmer_engine_jit::artifact::JITArtifact as wasmer_engine::artifact::Artifact>::register_frame_info (artifact.rs:275)
==11359== 
==11359== 1,152 bytes in 4 blocks are possibly lost in loss record 25 of 31
==11359==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11359==    by 0x4013666: allocate_dtv (dl-tls.c:286)
==11359==    by 0x4013666: _dl_allocate_tls (dl-tls.c:530)
==11359==    by 0x5252227: allocate_stack (allocatestack.c:627)
==11359==    by 0x5252227: pthread_create@@GLIBC_2.2.5 (pthread_create.c:644)
==11359==    by 0x1C476AC: std::sys::unix::thread::Thread::new (thread.rs:66)
==11359==    by 0xD7777B: std::thread::Builder::spawn_unchecked (mod.rs:492)
==11359==    by 0xD799FB: std::thread::Builder::spawn (mod.rs:386)
==11359==    by 0xD484E8: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11359==    by 0xD4962F: rayon_core::registry::Registry::new (registry.rs:256)
==11359==    by 0xD4875D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11359==    by 0xD48C19: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11359==    by 0xD6C2E3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11359==    by 0x1C326D9: std::sync::once::Once::call_inner (once.rs:416)
==11359== 
==11359== 1,520 bytes in 1 blocks are still reachable in loss record 26 of 31
==11359==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11359==    by 0xD7223B: alloc::alloc::alloc (alloc.rs:80)
==11359==    by 0xD73063: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11359==    by 0xD7219C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11359==    by 0xD58AC1: new<crossbeam_deque::deque::Block<rayon_core::job::JobRef>> (boxed.rs:177)
==11359==    by 0xD58AC1: <crossbeam_deque::deque::Injector<T> as core::default::Default>::default (deque.rs:1187)
==11359==    by 0xD5734D: crossbeam_deque::deque::Injector<T>::new (deque.rs:1213)
==11359==    by 0xD48FF3: rayon_core::registry::Registry::new (registry.rs:238)
==11359==    by 0xD4875D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11359==    by 0xD48C19: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11359==    by 0xD6C2E3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11359==    by 0x1C326D9: std::sync::once::Once::call_inner (once.rs:416)
==11359==    by 0xD6C080: std::sync::once::Once::call_once (once.rs:264)
==11359== 
==11359== 1,536 bytes in 4 blocks are still reachable in loss record 27 of 31
==11359==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11359==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11359==    by 0x1C37A99: aligned_malloc (alloc.rs:95)
==11359==    by 0x1C37A99: alloc (alloc.rs:22)
==11359==    by 0x1C37A99: __rdl_alloc (alloc.rs:304)
==11359==    by 0xD7223B: alloc::alloc::alloc (alloc.rs:80)
==11359==    by 0xD73063: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11359==    by 0xD7219C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11359==    by 0xD41CF5: alloc::sync::Arc<T>::new (sync.rs:324)
==11359==    by 0xD56E7D: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:250)
==11359==    by 0xD49AAE: rayon_core::registry::Registry::new::{{closure}} (registry.rs:225)
==11359==    by 0xD827FC: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11359==    by 0xD51B7D: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11359==    by 0xD83DB3: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11359== 
==11359== 2,008 bytes in 1 blocks are still reachable in loss record 28 of 31
==11359==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11359==    by 0xDB52EB: alloc::alloc::alloc (alloc.rs:80)
==11359==    by 0xDB5833: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11359==    by 0xDB524C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11359==    by 0xDADC09: new<crossbeam_epoch::sync::queue::Node<crossbeam_epoch::internal::SealedBag>> (boxed.rs:177)
==11359==    by 0xDADC09: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==11359==    by 0xDAD5B5: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==11359==    by 0xDAD505: crossbeam_epoch::atomic::Owned<T>::new (atomic.rs:846)
==11359==    by 0xDADE0B: crossbeam_epoch::sync::queue::Queue<T>::new (queue.rs:50)
==11359==    by 0xDA9203: crossbeam_epoch::internal::Global::new (internal.rs:254)
==11359==    by 0xDB19FB: <crossbeam_epoch::collector::Collector as core::default::Default>::default (collector.rs:32)
==11359==    by 0xDB1A36: crossbeam_epoch::collector::Collector::new (collector.rs:40)
==11359==    by 0xDAFF29: __static_ref_initialize (default.rs:13)
==11359==    by 0xDAFF29: core::ops::function::FnOnce::call_once (function.rs:233)
==11359== 
==11359== 4,096 bytes in 4 blocks are still reachable in loss record 29 of 31
==11359==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11359==    by 0xD7223B: alloc::alloc::alloc (alloc.rs:80)
==11359==    by 0xD73063: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11359==    by 0xD8B74D: alloc::raw_vec::RawVec<T,A>::allocate_in (raw_vec.rs:183)
==11359==    by 0xD8ECB0: alloc::raw_vec::RawVec<T,A>::with_capacity_in (raw_vec.rs:159)
==11359==    by 0xD8AE2E: alloc::raw_vec::RawVec<T>::with_capacity (raw_vec.rs:90)
==11359==    by 0xD6664E: alloc::vec::Vec<T>::with_capacity (vec.rs:363)
==11359==    by 0xD55890: crossbeam_deque::deque::Buffer<T>::alloc (deque.rs:45)
==11359==    by 0xD56D69: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:248)
==11359==    by 0xD49AAE: rayon_core::registry::Registry::new::{{closure}} (registry.rs:225)
==11359==    by 0xD827FC: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11359==    by 0xD51B7D: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11359== 
==11359== 4,560 bytes in 3 blocks are still reachable in loss record 30 of 31
==11359==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11359==    by 0xD7223B: alloc::alloc::alloc (alloc.rs:80)
==11359==    by 0xD73063: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11359==    by 0xD7219C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11359==    by 0xD58AC1: new<crossbeam_deque::deque::Block<rayon_core::job::JobRef>> (boxed.rs:177)
==11359==    by 0xD58AC1: <crossbeam_deque::deque::Injector<T> as core::default::Default>::default (deque.rs:1187)
==11359==    by 0xD5734D: crossbeam_deque::deque::Injector<T>::new (deque.rs:1213)
==11359==    by 0xD4372C: rayon_core::job::JobFifo::new (job.rs:193)
==11359==    by 0xD4BA4A: rayon_core::registry::main_loop (registry.rs:802)
==11359==    by 0xD4801F: rayon_core::registry::ThreadBuilder::run (registry.rs:55)
==11359==    by 0xD486D0: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}} (registry.rs:100)
==11359==    by 0xD810FF: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==11359==    by 0xD79900: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}} (mod.rs:475)
==11359== 
==11359== 6,120 bytes in 3 blocks are still reachable in loss record 31 of 31
==11359==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11359==    by 0xDB52EB: alloc::alloc::alloc (alloc.rs:80)
==11359==    by 0xDB5833: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11359==    by 0xDB524C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11359==    by 0xDA8C39: new<crossbeam_epoch::internal::Local> (boxed.rs:177)
==11359==    by 0xDA8C39: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==11359==    by 0xDAD555: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==11359==    by 0xDAD4B5: crossbeam_epoch::atomic::Owned<T>::new (atomic.rs:846)
==11359==    by 0xDA9AA2: crossbeam_epoch::internal::Local::register (internal.rs:392)
==11359==    by 0xDB1A5D: crossbeam_epoch::collector::Collector::register (collector.rs:45)
==11359==    by 0xDB0843: crossbeam_epoch::default::HANDLE::__init (default.rs:18)
==11359==    by 0xDAFF08: core::ops::function::FnOnce::call_once (function.rs:233)
==11359==    by 0xDB59DB: std::thread::local::lazy::LazyKeyInner<T>::initialize (local.rs:289)
==11359== 
==11359== LEAK SUMMARY:
==11359==    definitely lost: 0 bytes in 0 blocks
==11359==    indirectly lost: 0 bytes in 0 blocks
==11359==      possibly lost: 1,152 bytes in 4 blocks
==11359==    still reachable: 25,608 bytes in 83 blocks
==11359==         suppressed: 0 bytes in 0 blocks
==11359== 
==11359== For counts of detected and suppressed errors, rerun with: -v
==11359== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
