==13722== Memcheck, a memory error detector
==13722== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==13722== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==13722== Command: /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors
==13722== 
==13722== Conditional jump or move depends on uninitialised value(s)
==13722==    at 0x689A5D: wasmparser::validator::Validator::end (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x67F55C: wasmparser::validator::Validator::payload (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x67E7D1: wasmparser::validator::Validator::validate_all (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x297C9C: wasmer_compiler::compiler::Compiler::validate_module (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x263338: <wasmer_engine_jit::engine::JITEngine as wasmer_engine::engine::Engine>::validate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x57ABE4: wasmer::module::Module::from_binary (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x25C0C1: wasmer::module::Module::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x25D1F0: errors::main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x25BCE2: std::rt::lang_start::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x72BB92: {{closure}} (rt.rs:52)
==13722==    by 0x72BB92: do_call<closure-0,i32> (panicking.rs:348)
==13722==    by 0x72BB92: try<i32,closure-0> (panicking.rs:325)
==13722==    by 0x72BB92: catch_unwind<closure-0,i32> (panic.rs:394)
==13722==    by 0x72BB92: std::rt::lang_start_internal (rt.rs:51)
==13722==    by 0x25DCA1: main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==  Uninitialised value was created by a stack allocation
==13722==    at 0x297BB0: wasmer_compiler::compiler::Compiler::validate_module (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722== 
==13722== valgrind: Unrecognised instruction at address 0x4040016.
==13722==    at 0x4040016: ???
==13722==    by 0x4040041: ???
==13722==    by 0x4040095: ???
==13722==    by 0x6B6DF0: RegisterSetjmp (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x6AC027: std::thread::local::LocalKey<T>::with (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x6B3514: wasmer_vm::trap::traphandlers::wasmer_call_trampoline (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x25DE92: wasmer::native::NativeFunc<(),Rets>::call (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x25D6D4: errors::main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x25BCE2: std::rt::lang_start::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x72BB92: {{closure}} (rt.rs:52)
==13722==    by 0x72BB92: do_call<closure-0,i32> (panicking.rs:348)
==13722==    by 0x72BB92: try<i32,closure-0> (panicking.rs:325)
==13722==    by 0x72BB92: catch_unwind<closure-0,i32> (panic.rs:394)
==13722==    by 0x72BB92: std::rt::lang_start_internal (rt.rs:51)
==13722==    by 0x25DCA1: main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722== Your program just tried to execute an instruction that Valgrind
==13722== did not recognise.  There are two possible reasons for this.
==13722== 1. Your program has a bug and erroneously jumped to a non-code
==13722==    location.  If you are running Memcheck and you just saw a
==13722==    warning about a bad jump, it's probably your program's fault.
==13722== 2. The instruction is legitimate but Valgrind doesn't handle it,
==13722==    i.e. it's Valgrind's fault.  If you think this is the case or
==13722==    you are not sure, please let us know and we'll try to fix it.
==13722== Either way, Valgrind will now raise a SIGILL signal which will
==13722== probably kill your program.
==13722== Warning: client switching stacks?  SP change: 0x4051f68 --> 0x1ffefff400
==13722==          to suppress, use: --max-stackframe=137354728600 or greater
==13722== 
==13722== HEAP SUMMARY:
==13722==     in use at exit: 31,988 bytes in 106 blocks
==13722==   total heap usage: 738 allocs, 632 frees, 127,177 bytes allocated
==13722== 
==13722== 8 bytes in 1 blocks are still reachable in loss record 1 of 46
==13722==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x65FDD0: alloc::raw_vec::RawVec<T,A>::reserve_exact (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x6573C6: wasmer_compiler::translator::sections::parse_function_section (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x664864: wasmer_compiler::translator::module::translate_module (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x65AD98: wasmer_compiler::translator::environ::ModuleEnvironment::translate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x282274: wasmer_engine_jit::artifact::JITArtifact::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2634EA: <wasmer_engine_jit::engine::JITEngine as wasmer_engine::engine::Engine>::compile (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x57AC3F: wasmer::module::Module::from_binary (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x25C0C1: wasmer::module::Module::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x25D1F0: errors::main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x25BCE2: std::rt::lang_start::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x72BB92: {{closure}} (rt.rs:52)
==13722==    by 0x72BB92: do_call<closure-0,i32> (panicking.rs:348)
==13722==    by 0x72BB92: try<i32,closure-0> (panicking.rs:325)
==13722==    by 0x72BB92: catch_unwind<closure-0,i32> (panic.rs:394)
==13722==    by 0x72BB92: std::rt::lang_start_internal (rt.rs:51)
==13722== 
==13722== 8 bytes in 1 blocks are still reachable in loss record 2 of 46
==13722==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x2E23EA: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x725239: std::sync::once::Once::call_inner (once.rs:416)
==13722==    by 0x2DE980: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E177B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x28A961: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x291505: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x295CB8: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2B1701: rayon::result::<impl rayon::iter::FromParallelIterator<core::result::Result<T,E>> for core::result::Result<C,E>>::from_par_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x29E131: <wasmer_compiler_cranelift::compiler::CraneliftCompiler as wasmer_compiler::compiler::Compiler>::compile_module (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x282758: wasmer_engine_jit::artifact::JITArtifact::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2634EA: <wasmer_engine_jit::engine::JITEngine as wasmer_engine::engine::Engine>::compile (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722== 
==13722== 11 bytes in 1 blocks are still reachable in loss record 3 of 46
==13722==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x65B94F: wasmer_compiler::translator::environ::ModuleEnvironment::declare_func_export (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x65861B: wasmer_compiler::translator::sections::parse_export_section (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x664DED: wasmer_compiler::translator::module::translate_module (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x65AD98: wasmer_compiler::translator::environ::ModuleEnvironment::translate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x282274: wasmer_engine_jit::artifact::JITArtifact::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2634EA: <wasmer_engine_jit::engine::JITEngine as wasmer_engine::engine::Engine>::compile (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x57AC3F: wasmer::module::Module::from_binary (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x25C0C1: wasmer::module::Module::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x25D1F0: errors::main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x25BCE2: std::rt::lang_start::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x72BB92: {{closure}} (rt.rs:52)
==13722==    by 0x72BB92: do_call<closure-0,i32> (panicking.rs:348)
==13722==    by 0x72BB92: try<i32,closure-0> (panicking.rs:325)
==13722==    by 0x72BB92: catch_unwind<closure-0,i32> (panic.rs:394)
==13722==    by 0x72BB92: std::rt::lang_start_internal (rt.rs:51)
==13722== 
==13722== 16 bytes in 1 blocks are still reachable in loss record 4 of 46
==13722==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x6BD958: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x725239: std::sync::once::Once::call_inner (once.rs:416)
==13722==    by 0x6C2196: backtrace::lock::lock (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x6CA2E0: backtrace::backtrace::trace (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x6BCEA5: backtrace::capture::Backtrace::new_unresolved (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x6ABEA9: std::thread::local::LocalKey<T>::with (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x6B38B0: wasmer_vm::trap::traphandlers::trap_handler (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x525C97F: ??? (in /lib/x86_64-linux-gnu/libpthread-2.27.so)
==13722==    by 0x4040015: ???
==13722== 
==13722== 16 bytes in 2 blocks are still reachable in loss record 5 of 46
==13722==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x660BC1: alloc::raw_vec::RawVec<T,A>::reserve (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x6568D4: wasmer_compiler::translator::sections::parse_type_section (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x664B7F: wasmer_compiler::translator::module::translate_module (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x65AD98: wasmer_compiler::translator::environ::ModuleEnvironment::translate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x282274: wasmer_engine_jit::artifact::JITArtifact::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2634EA: <wasmer_engine_jit::engine::JITEngine as wasmer_engine::engine::Engine>::compile (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x57AC3F: wasmer::module::Module::from_binary (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x25C0C1: wasmer::module::Module::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x25D1F0: errors::main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x25BCE2: std::rt::lang_start::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x72BB92: {{closure}} (rt.rs:52)
==13722==    by 0x72BB92: do_call<closure-0,i32> (panicking.rs:348)
==13722==    by 0x72BB92: try<i32,closure-0> (panicking.rs:325)
==13722==    by 0x72BB92: catch_unwind<closure-0,i32> (panic.rs:394)
==13722==    by 0x72BB92: std::rt::lang_start_internal (rt.rs:51)
==13722== 
==13722== 16 bytes in 1 blocks are indirectly lost in loss record 6 of 46
==13722==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x2616D6: <alloc::boxed::Box<[T]> as core::clone::Clone>::clone (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x27EB3A: wasmer_engine::artifact::Artifact::instantiate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x57AF9D: wasmer::module::Module::instantiate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x580792: wasmer::instance::Instance::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x25D34C: errors::main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x25BCE2: std::rt::lang_start::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x72BB92: {{closure}} (rt.rs:52)
==13722==    by 0x72BB92: do_call<closure-0,i32> (panicking.rs:348)
==13722==    by 0x72BB92: try<i32,closure-0> (panicking.rs:325)
==13722==    by 0x72BB92: catch_unwind<closure-0,i32> (panic.rs:394)
==13722==    by 0x72BB92: std::rt::lang_start_internal (rt.rs:51)
==13722==    by 0x25DCA1: main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722== 
==13722== 16 bytes in 1 blocks are indirectly lost in loss record 7 of 46
==13722==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x2615E6: <alloc::boxed::Box<[T]> as core::clone::Clone>::clone (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x27EB67: wasmer_engine::artifact::Artifact::instantiate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x57AF9D: wasmer::module::Module::instantiate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x580792: wasmer::instance::Instance::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x25D34C: errors::main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x25BCE2: std::rt::lang_start::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x72BB92: {{closure}} (rt.rs:52)
==13722==    by 0x72BB92: do_call<closure-0,i32> (panicking.rs:348)
==13722==    by 0x72BB92: try<i32,closure-0> (panicking.rs:325)
==13722==    by 0x72BB92: catch_unwind<closure-0,i32> (panic.rs:394)
==13722==    by 0x72BB92: std::rt::lang_start_internal (rt.rs:51)
==13722==    by 0x25DCA1: main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722== 
==13722== 29 bytes in 2 blocks are still reachable in loss record 8 of 46
==13722==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x65BDCF: wasmer_compiler::translator::environ::ModuleEnvironment::declare_function_name (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x659DC2: wasmer_compiler::translator::sections::parse_name_section (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x664FE0: wasmer_compiler::translator::module::translate_module (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x65AD98: wasmer_compiler::translator::environ::ModuleEnvironment::translate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x282274: wasmer_engine_jit::artifact::JITArtifact::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2634EA: <wasmer_engine_jit::engine::JITEngine as wasmer_engine::engine::Engine>::compile (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x57AC3F: wasmer::module::Module::from_binary (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x25C0C1: wasmer::module::Module::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x25D1F0: errors::main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x25BCE2: std::rt::lang_start::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x72BB92: {{closure}} (rt.rs:52)
==13722==    by 0x72BB92: do_call<closure-0,i32> (panicking.rs:348)
==13722==    by 0x72BB92: try<i32,closure-0> (panicking.rs:325)
==13722==    by 0x72BB92: catch_unwind<closure-0,i32> (panic.rs:394)
==13722==    by 0x72BB92: std::rt::lang_start_internal (rt.rs:51)
==13722== 
==13722== 32 bytes in 1 blocks are still reachable in loss record 9 of 46
==13722==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x4E3F7F4: _dlerror_run (dlerror.c:140)
==13722==    by 0x4E3F165: dlsym (dlsym.c:70)
==13722==    by 0x73A163: fetch (weak.rs:61)
==13722==    by 0x73A163: get<unsafe extern "C" fn(*const libc::unix::linux_like::linux::gnu::b64::x86_64::pthread_attr_t) -> usize> (weak.rs:46)
==13722==    by 0x73A163: min_stack_size (thread.rs:449)
==13722==    by 0x73A163: std::sys::unix::thread::Thread::new (thread.rs:49)
==13722==    by 0x2DB486: std::thread::Builder::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DE806: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DF3BF: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E23B6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x725239: std::sync::once::Once::call_inner (once.rs:416)
==13722==    by 0x2DE980: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E177B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x28A961: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722== 
==13722== 32 bytes in 1 blocks are still reachable in loss record 10 of 46
==13722==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==13722==    by 0x2ED0BD: _ZN3std6thread5local4fast12Key$LT$T$GT$14try_initialize17h3d6d30c5335b0a67E.llvm.12191645446024711930 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E4B92: crossbeam_deque::deque::Stealer<T>::steal (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DC52B: <core::iter::adapters::chain::Chain<A,B> as core::iter::traits::iterator::Iterator>::try_fold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E00D9: rayon_core::registry::WorkerThread::wait_until_cold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DE1EA: rayon_core::registry::ThreadBuilder::run (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E0C80: _ZN3std10sys_common9backtrace28__rust_begin_short_backtrace17hd13678e4d803656bE.llvm.9549009445676040077 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DB64E: core::ops::function::FnOnce::call_once{{vtable-shim}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x73A4D9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==13722==    by 0x73A4D9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==13722==    by 0x73A4D9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==13722==    by 0x52516DA: start_thread (pthread_create.c:463)
==13722==    by 0x57A271E: clone (clone.S:95)
==13722== 
==13722== 40 bytes in 1 blocks are still reachable in loss record 11 of 46
==13722==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x6C993B: std::sync::mutex::Mutex<T>::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x6BD948: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x725239: std::sync::once::Once::call_inner (once.rs:416)
==13722==    by 0x6C2196: backtrace::lock::lock (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x6CA2E0: backtrace::backtrace::trace (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x6BCEA5: backtrace::capture::Backtrace::new_unresolved (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x6ABEA9: std::thread::local::LocalKey<T>::with (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x6B38B0: wasmer_vm::trap::traphandlers::trap_handler (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x525C97F: ??? (in /lib/x86_64-linux-gnu/libpthread-2.27.so)
==13722==    by 0x4040015: ???
==13722== 
==13722== 52 bytes in 1 blocks are possibly lost in loss record 12 of 46
==13722==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x653BA2: hashbrown::raw::inner::RawTable<T>::fallible_with_capacity (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x6535BE: _ZN9hashbrown3raw5inner17RawTable$LT$T$GT$14reserve_rehash17he29be5fc862d84d8E.llvm.8588116468508767673 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x658751: wasmer_compiler::translator::sections::parse_export_section (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x664DED: wasmer_compiler::translator::module::translate_module (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x65AD98: wasmer_compiler::translator::environ::ModuleEnvironment::translate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x282274: wasmer_engine_jit::artifact::JITArtifact::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2634EA: <wasmer_engine_jit::engine::JITEngine as wasmer_engine::engine::Engine>::compile (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x57AC3F: wasmer::module::Module::from_binary (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x25C0C1: wasmer::module::Module::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x25D1F0: errors::main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x25BCE2: std::rt::lang_start::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722== 
==13722== 64 bytes in 4 blocks are still reachable in loss record 13 of 46
==13722==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x2E49EC: crossbeam_deque::deque::Worker<T>::new_lifo (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E5867: core::iter::traits::iterator::Iterator::unzip (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DEC96: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E23B6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x725239: std::sync::once::Once::call_inner (once.rs:416)
==13722==    by 0x2DE980: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E177B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x28A961: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x291505: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x295CB8: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2B1701: rayon::result::<impl rayon::iter::FromParallelIterator<core::result::Result<T,E>> for core::result::Result<C,E>>::from_par_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722== 
==13722== 64 bytes in 4 blocks are still reachable in loss record 14 of 46
==13722==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x73A0BC: alloc (alloc.rs:80)
==13722==    by 0x73A0BC: alloc (alloc.rs:174)
==13722==    by 0x73A0BC: exchange_malloc (alloc.rs:277)
==13722==    by 0x73A0BC: std::sys::unix::thread::Thread::new (thread.rs:44)
==13722==    by 0x2DB486: std::thread::Builder::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DE806: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DF3BF: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E23B6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x725239: std::sync::once::Once::call_inner (once.rs:416)
==13722==    by 0x2DE980: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E177B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x28A961: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x291505: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x295CB8: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722== 
==13722== 72 bytes in 1 blocks are still reachable in loss record 15 of 46
==13722==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x64129D: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x725239: std::sync::once::Once::call_inner (once.rs:416)
==13722==    by 0x644F0B: wasmer_engine::trap::frame_info::register (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x284815: <wasmer_engine_jit::artifact::JITArtifact as wasmer_engine::artifact::Artifact>::register_frame_info (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x27EAF5: wasmer_engine::artifact::Artifact::instantiate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x57AF9D: wasmer::module::Module::instantiate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x580792: wasmer::instance::Instance::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x25D34C: errors::main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x25BCE2: std::rt::lang_start::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x72BB92: {{closure}} (rt.rs:52)
==13722==    by 0x72BB92: do_call<closure-0,i32> (panicking.rs:348)
==13722==    by 0x72BB92: try<i32,closure-0> (panicking.rs:325)
==13722==    by 0x72BB92: catch_unwind<closure-0,i32> (panic.rs:394)
==13722==    by 0x72BB92: std::rt::lang_start_internal (rt.rs:51)
==13722==    by 0x25DCA1: main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722== 
==13722== 96 bytes in 1 blocks are still reachable in loss record 16 of 46
==13722==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x65FCD7: alloc::raw_vec::RawVec<T,A>::reserve_exact (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x656687: wasmer_compiler::translator::sections::parse_type_section (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x664B7F: wasmer_compiler::translator::module::translate_module (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x65AD98: wasmer_compiler::translator::environ::ModuleEnvironment::translate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x282274: wasmer_engine_jit::artifact::JITArtifact::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2634EA: <wasmer_engine_jit::engine::JITEngine as wasmer_engine::engine::Engine>::compile (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x57AC3F: wasmer::module::Module::from_binary (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x25C0C1: wasmer::module::Module::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x25D1F0: errors::main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x25BCE2: std::rt::lang_start::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x72BB92: {{closure}} (rt.rs:52)
==13722==    by 0x72BB92: do_call<closure-0,i32> (panicking.rs:348)
==13722==    by 0x72BB92: try<i32,closure-0> (panicking.rs:325)
==13722==    by 0x72BB92: catch_unwind<closure-0,i32> (panic.rs:394)
==13722==    by 0x72BB92: std::rt::lang_start_internal (rt.rs:51)
==13722== 
==13722== 96 bytes in 3 blocks are still reachable in loss record 17 of 46
==13722==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==13722==    by 0x2ED0BD: _ZN3std6thread5local4fast12Key$LT$T$GT$14try_initialize17h3d6d30c5335b0a67E.llvm.12191645446024711930 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E4B92: crossbeam_deque::deque::Stealer<T>::steal (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DC496: <core::iter::adapters::chain::Chain<A,B> as core::iter::traits::iterator::Iterator>::try_fold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E00D9: rayon_core::registry::WorkerThread::wait_until_cold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DE1EA: rayon_core::registry::ThreadBuilder::run (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E0C80: _ZN3std10sys_common9backtrace28__rust_begin_short_backtrace17hd13678e4d803656bE.llvm.9549009445676040077 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DB64E: core::ops::function::FnOnce::call_once{{vtable-shim}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x73A4D9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==13722==    by 0x73A4D9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==13722==    by 0x73A4D9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==13722==    by 0x52516DA: start_thread (pthread_create.c:463)
==13722==    by 0x57A271E: clone (clone.S:95)
==13722== 
==13722== 120 bytes in 1 blocks are still reachable in loss record 18 of 46
==13722==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x65FBD7: alloc::raw_vec::RawVec<T,A>::reserve_exact (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x6584A3: wasmer_compiler::translator::sections::parse_export_section (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x664DED: wasmer_compiler::translator::module::translate_module (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x65AD98: wasmer_compiler::translator::environ::ModuleEnvironment::translate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x282274: wasmer_engine_jit::artifact::JITArtifact::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2634EA: <wasmer_engine_jit::engine::JITEngine as wasmer_engine::engine::Engine>::compile (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x57AC3F: wasmer::module::Module::from_binary (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x25C0C1: wasmer::module::Module::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x25D1F0: errors::main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x25BCE2: std::rt::lang_start::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x72BB92: {{closure}} (rt.rs:52)
==13722==    by 0x72BB92: do_call<closure-0,i32> (panicking.rs:348)
==13722==    by 0x72BB92: try<i32,closure-0> (panicking.rs:325)
==13722==    by 0x72BB92: catch_unwind<closure-0,i32> (panic.rs:394)
==13722==    by 0x72BB92: std::rt::lang_start_internal (rt.rs:51)
==13722== 
==13722== 128 bytes in 4 blocks are still reachable in loss record 19 of 46
==13722==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==13722==    by 0x7066EE: register_dtor (fast_thread_local.rs:33)
==13722==    by 0x7066EE: try_register_dtor<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:438)
==13722==    by 0x7066EE: std::thread::local::fast::Key<T>::try_initialize (local.rs:424)
==13722==    by 0x728EE9: get<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,fn() -> core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:410)
==13722==    by 0x728EE9: __getit (local.rs:175)
==13722==    by 0x728EE9: try_with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:262)
==13722==    by 0x728EE9: with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:239)
==13722==    by 0x728EE9: std::sys_common::thread_info::set (thread_info.rs:40)
==13722==    by 0x2DB60C: core::ops::function::FnOnce::call_once{{vtable-shim}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x73A4D9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==13722==    by 0x73A4D9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==13722==    by 0x73A4D9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==13722==    by 0x52516DA: start_thread (pthread_create.c:463)
==13722==    by 0x57A271E: clone (clone.S:95)
==13722== 
==13722== 152 bytes in 1 blocks are still reachable in loss record 20 of 46
==13722==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x66317F: hashbrown::raw::RawTable<T>::reserve_rehash (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x663522: hashbrown::raw::RawTable<T>::insert (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x652734: hashbrown::map::HashMap<K,V,S>::insert (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x65BE54: wasmer_compiler::translator::environ::ModuleEnvironment::declare_function_name (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x659DC2: wasmer_compiler::translator::sections::parse_name_section (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x664FE0: wasmer_compiler::translator::module::translate_module (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x65AD98: wasmer_compiler::translator::environ::ModuleEnvironment::translate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x282274: wasmer_engine_jit::artifact::JITArtifact::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2634EA: <wasmer_engine_jit::engine::JITEngine as wasmer_engine::engine::Engine>::compile (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x57AC3F: wasmer::module::Module::from_binary (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x25C0C1: wasmer::module::Module::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722== 
==13722== 160 bytes in 4 blocks are still reachable in loss record 21 of 46
==13722==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x2E267C: std::sync::mutex::Mutex<T>::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DFCDB: rayon_core::registry::ThreadInfo::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E5AC8: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E0C10: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DED3A: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E23B6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x725239: std::sync::once::Once::call_inner (once.rs:416)
==13722==    by 0x2DE980: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E177B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x28A961: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x291505: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722== 
==13722== 160 bytes in 4 blocks are still reachable in loss record 22 of 46
==13722==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x2E267C: std::sync::mutex::Mutex<T>::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DFD06: rayon_core::registry::ThreadInfo::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E5AC8: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E0C10: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DED3A: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E23B6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x725239: std::sync::once::Once::call_inner (once.rs:416)
==13722==    by 0x2DE980: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E177B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x28A961: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x291505: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722== 
==13722== 160 bytes in 4 blocks are still reachable in loss record 23 of 46
==13722==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x2E267C: std::sync::mutex::Mutex<T>::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E5C8B: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DEDB0: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E23B6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x725239: std::sync::once::Once::call_inner (once.rs:416)
==13722==    by 0x2DE980: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E177B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x28A961: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x291505: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x295CB8: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2B1701: rayon::result::<impl rayon::iter::FromParallelIterator<core::result::Result<T,E>> for core::result::Result<C,E>>::from_par_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722== 
==13722== 160 bytes in 4 blocks are still reachable in loss record 24 of 46
==13722==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x707A8E: alloc (alloc.rs:80)
==13722==    by 0x707A8E: alloc (alloc.rs:174)
==13722==    by 0x707A8E: exchange_malloc (alloc.rs:277)
==13722==    by 0x707A8E: new<()> (mutex.rs:223)
==13722==    by 0x707A8E: std::thread::Thread::new (mod.rs:1149)
==13722==    by 0x2DB371: std::thread::Builder::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DE806: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DF3BF: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E23B6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x725239: std::sync::once::Once::call_inner (once.rs:416)
==13722==    by 0x2DE980: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E177B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x28A961: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x291505: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x295CB8: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722== 
==13722== 160 bytes in 4 blocks are still reachable in loss record 25 of 46
==13722==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x2DB393: std::thread::Builder::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DE806: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DF3BF: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E23B6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x725239: std::sync::once::Once::call_inner (once.rs:416)
==13722==    by 0x2DE980: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E177B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x28A961: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x291505: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x295CB8: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2B1701: rayon::result::<impl rayon::iter::FromParallelIterator<core::result::Result<T,E>> for core::result::Result<C,E>>::from_par_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722== 
==13722== 192 bytes in 4 blocks are still reachable in loss record 26 of 46
==13722==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x724B86: alloc (alloc.rs:80)
==13722==    by 0x724B86: alloc (alloc.rs:174)
==13722==    by 0x724B86: exchange_malloc (alloc.rs:277)
==13722==    by 0x724B86: std::sync::condvar::Condvar::new (condvar.rs:130)
==13722==    by 0x2DFCE6: rayon_core::registry::ThreadInfo::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E5AC8: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E0C10: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DED3A: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E23B6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x725239: std::sync::once::Once::call_inner (once.rs:416)
==13722==    by 0x2DE980: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E177B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x28A961: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x291505: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722== 
==13722== 192 bytes in 4 blocks are still reachable in loss record 27 of 46
==13722==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x724B86: alloc (alloc.rs:80)
==13722==    by 0x724B86: alloc (alloc.rs:174)
==13722==    by 0x724B86: exchange_malloc (alloc.rs:277)
==13722==    by 0x724B86: std::sync::condvar::Condvar::new (condvar.rs:130)
==13722==    by 0x2DFD11: rayon_core::registry::ThreadInfo::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E5AC8: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E0C10: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DED3A: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E23B6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x725239: std::sync::once::Once::call_inner (once.rs:416)
==13722==    by 0x2DE980: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E177B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x28A961: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x291505: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722== 
==13722== 192 bytes in 4 blocks are still reachable in loss record 28 of 46
==13722==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x724B86: alloc (alloc.rs:80)
==13722==    by 0x724B86: alloc (alloc.rs:174)
==13722==    by 0x724B86: exchange_malloc (alloc.rs:277)
==13722==    by 0x724B86: std::sync::condvar::Condvar::new (condvar.rs:130)
==13722==    by 0x2E5C91: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DEDB0: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E23B6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x725239: std::sync::once::Once::call_inner (once.rs:416)
==13722==    by 0x2DE980: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E177B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x28A961: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x291505: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x295CB8: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2B1701: rayon::result::<impl rayon::iter::FromParallelIterator<core::result::Result<T,E>> for core::result::Result<C,E>>::from_par_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722== 
==13722== 192 bytes in 4 blocks are still reachable in loss record 29 of 46
==13722==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x707AF2: alloc (alloc.rs:80)
==13722==    by 0x707AF2: alloc (alloc.rs:174)
==13722==    by 0x707AF2: exchange_malloc (alloc.rs:277)
==13722==    by 0x707AF2: new (condvar.rs:130)
==13722==    by 0x707AF2: std::thread::Thread::new (mod.rs:1150)
==13722==    by 0x2DB371: std::thread::Builder::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DE806: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DF3BF: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E23B6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x725239: std::sync::once::Once::call_inner (once.rs:416)
==13722==    by 0x2DE980: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E177B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x28A961: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x291505: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x295CB8: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722== 
==13722== 320 bytes in 4 blocks are still reachable in loss record 30 of 46
==13722==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x707B41: alloc (alloc.rs:80)
==13722==    by 0x707B41: alloc (alloc.rs:174)
==13722==    by 0x707B41: exchange_malloc (alloc.rs:277)
==13722==    by 0x707B41: new<std::thread::Inner> (sync.rs:324)
==13722==    by 0x707B41: std::thread::Thread::new (mod.rs:1145)
==13722==    by 0x2DB371: std::thread::Builder::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DE806: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DF3BF: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E23B6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x725239: std::sync::once::Once::call_inner (once.rs:416)
==13722==    by 0x2DE980: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E177B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x28A961: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x291505: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x295CB8: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722== 
==13722== 384 bytes in 1 blocks are still reachable in loss record 31 of 46
==13722==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x2E3E9C: alloc::raw_vec::RawVec<T,A>::reserve (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E0BCC: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DED3A: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E23B6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x725239: std::sync::once::Once::call_inner (once.rs:416)
==13722==    by 0x2DE980: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E177B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x28A961: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x291505: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x295CB8: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2B1701: rayon::result::<impl rayon::iter::FromParallelIterator<core::result::Result<T,E>> for core::result::Result<C,E>>::from_par_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722== 
==13722== 416 bytes in 4 blocks are still reachable in loss record 32 of 46
==13722==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x2DB428: std::thread::Builder::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DE806: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DF3BF: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E23B6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x725239: std::sync::once::Once::call_inner (once.rs:416)
==13722==    by 0x2DE980: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E177B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x28A961: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x291505: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x295CB8: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2B1701: rayon::result::<impl rayon::iter::FromParallelIterator<core::result::Result<T,E>> for core::result::Result<C,E>>::from_par_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722== 
==13722== 448 (416 direct, 32 indirect) bytes in 1 blocks are definitely lost in loss record 33 of 46
==13722==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x6A8D2D: wasmer_vm::instance::InstanceHandle::allocate_instance (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x27E4C1: wasmer_engine::artifact::Artifact::instantiate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x57AF9D: wasmer::module::Module::instantiate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x580792: wasmer::instance::Instance::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x25D34C: errors::main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x25BCE2: std::rt::lang_start::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x72BB92: {{closure}} (rt.rs:52)
==13722==    by 0x72BB92: do_call<closure-0,i32> (panicking.rs:348)
==13722==    by 0x72BB92: try<i32,closure-0> (panicking.rs:325)
==13722==    by 0x72BB92: catch_unwind<closure-0,i32> (panic.rs:394)
==13722==    by 0x72BB92: std::rt::lang_start_internal (rt.rs:51)
==13722==    by 0x25DCA1: main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722== 
==13722== 512 bytes in 1 blocks are still reachable in loss record 34 of 46
==13722==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x72A5F9: aligned_malloc (alloc.rs:95)
==13722==    by 0x72A5F9: alloc (alloc.rs:22)
==13722==    by 0x72A5F9: __rdl_alloc (alloc.rs:304)
==13722==    by 0x2E41B6: alloc::raw_vec::RawVec<T,A>::reserve (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DED6A: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E23B6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x725239: std::sync::once::Once::call_inner (once.rs:416)
==13722==    by 0x2DE980: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E177B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x28A961: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x291505: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x295CB8: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722== 
==13722== 640 bytes in 1 blocks are still reachable in loss record 35 of 46
==13722==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x72A5F9: aligned_malloc (alloc.rs:95)
==13722==    by 0x72A5F9: alloc (alloc.rs:22)
==13722==    by 0x72A5F9: __rdl_alloc (alloc.rs:304)
==13722==    by 0x2DEFA6: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E23B6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x725239: std::sync::once::Once::call_inner (once.rs:416)
==13722==    by 0x2DE980: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E177B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x28A961: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x291505: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x295CB8: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2B1701: rayon::result::<impl rayon::iter::FromParallelIterator<core::result::Result<T,E>> for core::result::Result<C,E>>::from_par_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722== 
==13722== 640 bytes in 1 blocks are still reachable in loss record 36 of 46
==13722==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x72A5F9: aligned_malloc (alloc.rs:95)
==13722==    by 0x72A5F9: alloc (alloc.rs:22)
==13722==    by 0x72A5F9: __rdl_alloc (alloc.rs:304)
==13722==    by 0x2ED4C2: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x725239: std::sync::once::Once::call_inner (once.rs:416)
==13722==    by 0x2ED15D: _ZN3std6thread5local4fast12Key$LT$T$GT$14try_initialize17h3d6d30c5335b0a67E.llvm.12191645446024711930 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E4B92: crossbeam_deque::deque::Stealer<T>::steal (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DC496: <core::iter::adapters::chain::Chain<A,B> as core::iter::traits::iterator::Iterator>::try_fold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E00D9: rayon_core::registry::WorkerThread::wait_until_cold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DE1EA: rayon_core::registry::ThreadBuilder::run (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E0C80: _ZN3std10sys_common9backtrace28__rust_begin_short_backtrace17hd13678e4d803656bE.llvm.9549009445676040077 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DB64E: core::ops::function::FnOnce::call_once{{vtable-shim}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722== 
==13722== 664 bytes in 1 blocks are still reachable in loss record 37 of 46
==13722==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x2825E3: wasmer_engine_jit::artifact::JITArtifact::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2634EA: <wasmer_engine_jit::engine::JITEngine as wasmer_engine::engine::Engine>::compile (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x57AC3F: wasmer::module::Module::from_binary (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x25C0C1: wasmer::module::Module::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x25D1F0: errors::main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x25BCE2: std::rt::lang_start::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x72BB92: {{closure}} (rt.rs:52)
==13722==    by 0x72BB92: do_call<closure-0,i32> (panicking.rs:348)
==13722==    by 0x72BB92: try<i32,closure-0> (panicking.rs:325)
==13722==    by 0x72BB92: catch_unwind<closure-0,i32> (panic.rs:394)
==13722==    by 0x72BB92: std::rt::lang_start_internal (rt.rs:51)
==13722==    by 0x25DCA1: main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722== 
==13722== 808 bytes in 1 blocks are still reachable in loss record 38 of 46
==13722==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x64C7FF: alloc::collections::btree::map::BTreeMap<K,V>::insert (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x645311: wasmer_engine::trap::frame_info::register (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x284815: <wasmer_engine_jit::artifact::JITArtifact as wasmer_engine::artifact::Artifact>::register_frame_info (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x27EAF5: wasmer_engine::artifact::Artifact::instantiate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x57AF9D: wasmer::module::Module::instantiate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x580792: wasmer::instance::Instance::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x25D34C: errors::main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x25BCE2: std::rt::lang_start::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x72BB92: {{closure}} (rt.rs:52)
==13722==    by 0x72BB92: do_call<closure-0,i32> (panicking.rs:348)
==13722==    by 0x72BB92: try<i32,closure-0> (panicking.rs:325)
==13722==    by 0x72BB92: catch_unwind<closure-0,i32> (panic.rs:394)
==13722==    by 0x72BB92: std::rt::lang_start_internal (rt.rs:51)
==13722==    by 0x25DCA1: main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722== 
==13722== 1,152 bytes in 4 blocks are possibly lost in loss record 39 of 46
==13722==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x4013666: allocate_dtv (dl-tls.c:286)
==13722==    by 0x4013666: _dl_allocate_tls (dl-tls.c:530)
==13722==    by 0x5252227: allocate_stack (allocatestack.c:627)
==13722==    by 0x5252227: pthread_create@@GLIBC_2.2.5 (pthread_create.c:644)
==13722==    by 0x73A20C: std::sys::unix::thread::Thread::new (thread.rs:66)
==13722==    by 0x2DB486: std::thread::Builder::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DE806: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DF3BF: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E23B6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x725239: std::sync::once::Once::call_inner (once.rs:416)
==13722==    by 0x2DE980: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E177B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x28A961: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722== 
==13722== 1,520 bytes in 1 blocks are still reachable in loss record 40 of 46
==13722==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x2DEE02: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E23B6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x725239: std::sync::once::Once::call_inner (once.rs:416)
==13722==    by 0x2DE980: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E177B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x28A961: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x291505: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x295CB8: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2B1701: rayon::result::<impl rayon::iter::FromParallelIterator<core::result::Result<T,E>> for core::result::Result<C,E>>::from_par_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x29E131: <wasmer_compiler_cranelift::compiler::CraneliftCompiler as wasmer_compiler::compiler::Compiler>::compile_module (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x282758: wasmer_engine_jit::artifact::JITArtifact::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722== 
==13722== 1,536 bytes in 4 blocks are still reachable in loss record 41 of 46
==13722==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x72A5F9: aligned_malloc (alloc.rs:95)
==13722==    by 0x72A5F9: alloc (alloc.rs:22)
==13722==    by 0x72A5F9: __rdl_alloc (alloc.rs:304)
==13722==    by 0x2E4A90: crossbeam_deque::deque::Worker<T>::new_lifo (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E5867: core::iter::traits::iterator::Iterator::unzip (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DEC96: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E23B6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x725239: std::sync::once::Once::call_inner (once.rs:416)
==13722==    by 0x2DE980: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E177B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x28A961: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x291505: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722== 
==13722== 2,008 bytes in 1 blocks are still reachable in loss record 42 of 46
==13722==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x2ECC0E: crossbeam_epoch::sync::queue::Queue<T>::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2ED492: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x725239: std::sync::once::Once::call_inner (once.rs:416)
==13722==    by 0x2ED15D: _ZN3std6thread5local4fast12Key$LT$T$GT$14try_initialize17h3d6d30c5335b0a67E.llvm.12191645446024711930 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E4B92: crossbeam_deque::deque::Stealer<T>::steal (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DC496: <core::iter::adapters::chain::Chain<A,B> as core::iter::traits::iterator::Iterator>::try_fold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E00D9: rayon_core::registry::WorkerThread::wait_until_cold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DE1EA: rayon_core::registry::ThreadBuilder::run (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E0C80: _ZN3std10sys_common9backtrace28__rust_begin_short_backtrace17hd13678e4d803656bE.llvm.9549009445676040077 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DB64E: core::ops::function::FnOnce::call_once{{vtable-shim}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x73A4D9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==13722==    by 0x73A4D9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==13722==    by 0x73A4D9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==13722== 
==13722== 2,040 bytes in 1 blocks are still reachable in loss record 43 of 46
==13722==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x2EA4EF: crossbeam_epoch::internal::Local::register (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2ED0E4: _ZN3std6thread5local4fast12Key$LT$T$GT$14try_initialize17h3d6d30c5335b0a67E.llvm.12191645446024711930 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E4B92: crossbeam_deque::deque::Stealer<T>::steal (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DC52B: <core::iter::adapters::chain::Chain<A,B> as core::iter::traits::iterator::Iterator>::try_fold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E00D9: rayon_core::registry::WorkerThread::wait_until_cold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DE1EA: rayon_core::registry::ThreadBuilder::run (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E0C80: _ZN3std10sys_common9backtrace28__rust_begin_short_backtrace17hd13678e4d803656bE.llvm.9549009445676040077 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DB64E: core::ops::function::FnOnce::call_once{{vtable-shim}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x73A4D9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==13722==    by 0x73A4D9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==13722==    by 0x73A4D9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==13722==    by 0x52516DA: start_thread (pthread_create.c:463)
==13722==    by 0x57A271E: clone (clone.S:95)
==13722== 
==13722== 4,096 bytes in 4 blocks are still reachable in loss record 44 of 46
==13722==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x2E49D0: crossbeam_deque::deque::Worker<T>::new_lifo (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E5867: core::iter::traits::iterator::Iterator::unzip (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DEC96: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E23B6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x725239: std::sync::once::Once::call_inner (once.rs:416)
==13722==    by 0x2DE980: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E177B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x28A961: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x291505: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x295CB8: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2B1701: rayon::result::<impl rayon::iter::FromParallelIterator<core::result::Result<T,E>> for core::result::Result<C,E>>::from_par_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722== 
==13722== 6,080 bytes in 4 blocks are still reachable in loss record 45 of 46
==13722==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x2DDBB8: rayon_core::registry::ThreadBuilder::run (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E0C80: _ZN3std10sys_common9backtrace28__rust_begin_short_backtrace17hd13678e4d803656bE.llvm.9549009445676040077 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DB64E: core::ops::function::FnOnce::call_once{{vtable-shim}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x73A4D9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==13722==    by 0x73A4D9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==13722==    by 0x73A4D9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==13722==    by 0x52516DA: start_thread (pthread_create.c:463)
==13722==    by 0x57A271E: clone (clone.S:95)
==13722== 
==13722== 6,120 bytes in 3 blocks are still reachable in loss record 46 of 46
==13722==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13722==    by 0x2EA4EF: crossbeam_epoch::internal::Local::register (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2ED0E4: _ZN3std6thread5local4fast12Key$LT$T$GT$14try_initialize17h3d6d30c5335b0a67E.llvm.12191645446024711930 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E4B92: crossbeam_deque::deque::Stealer<T>::steal (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DC496: <core::iter::adapters::chain::Chain<A,B> as core::iter::traits::iterator::Iterator>::try_fold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E00D9: rayon_core::registry::WorkerThread::wait_until_cold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DE1EA: rayon_core::registry::ThreadBuilder::run (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2E0C80: _ZN3std10sys_common9backtrace28__rust_begin_short_backtrace17hd13678e4d803656bE.llvm.9549009445676040077 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x2DB64E: core::ops::function::FnOnce::call_once{{vtable-shim}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13722==    by 0x73A4D9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==13722==    by 0x73A4D9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==13722==    by 0x73A4D9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==13722==    by 0x52516DA: start_thread (pthread_create.c:463)
==13722==    by 0x57A271E: clone (clone.S:95)
==13722== 
==13722== LEAK SUMMARY:
==13722==    definitely lost: 416 bytes in 1 blocks
==13722==    indirectly lost: 32 bytes in 2 blocks
==13722==      possibly lost: 1,204 bytes in 5 blocks
==13722==    still reachable: 30,336 bytes in 98 blocks
==13722==         suppressed: 0 bytes in 0 blocks
==13722== 
==13722== For counts of detected and suppressed errors, rerun with: -v
==13722== ERROR SUMMARY: 4 errors from 4 contexts (suppressed: 0 from 0)
